### ISSUE TITLE
xbox controller open the version window on X Button (monster hunter wildes)

### ISSUE THREAD

**Issue by SevenGhost07** [optiscaler/OptiScaler#270]
hi,

my problem is, the X Button on the Xbox Controller open the version window from Optiscaler in monster hunter wildes. where can i change the full keybinde from optiscaler?

**Comment by cdozdil** [comment]
Hi,

There are some raports about gamepad issues, will check it 👍

**Comment by SevenGhost07** [comment]
little update: when press little bit longer than come the window^^

**Comment by mattiepee** [comment]
I have had it in Jedi Survivor and Spider-Man 2.  Probably some more.  I will try to re-create it...I did fix it at one point.  I will try to figure out what I did.

**Comment by SevenGhost07** [comment]
@mattiepee  that would be cool. its look like a keybinding problem.

**Comment by cdozdil** [comment]
Hi,

Could you guys check with latest nightly, issues sould be resolved now.

**Comment by mattiepee** [comment]
Unfortunately it is still happening.  There is something I am doing to stop it, but I am not seeing what it is.  

https://photos.app.goo.gl/koUDstNh587rKp4y9

**Comment by cdozdil** [comment]
Hi, 

If this happens after opening menu it's normal behavior of ImGui.

**Comment by mattiepee** [comment]
Is there a way to change that hot key from X?  I only see in Optiscaler.ini the ability to change the key to open the menu, which is INS by default.  As far as I am aware my controller's X button doesn't emulate any keyboard buttons.

**Comment by 4tl4sh** [comment]
Same here with Spiderman 2
