### ISSUE TITLE
No FSR4 on MSFS2024

### ISSUE THREAD

**Issue by ebisettia** [optiscaler/OptiScaler#625]
#### Mods and mod versions used 
OptiScaler_v0.7.7-pre9_20250425_102601

<img width="889" height="35" alt="Image" src="https://github.com/user-attachments/assets/30a82eb7-344f-4435-b938-b92b6e987b7b" />

<img width="3740" height="1529" alt="Image" src="https://github.com/user-attachments/assets/5fb1cae5-de08-4e27-ae66-a95035b124cf" />
<img width="1839" height="2020" alt="Image" src="https://github.com/user-attachments/assets/7bac9de5-29ad-4c5c-b90d-3cbc2f41e108" />

[OptiScaler.zip](https://github.com/user-attachments/files/21474395/OptiScaler.zip)

#### GPU
RX 9070XT

#### OS 
Win 11

#### Used automated or manual install?
 - [X] Automated

If on AMD/Intel and Automated, **used DLSS inputs**?
- [X] Yes
- [ ] No

#### Did you check the [Wiki](https://github.com/optiscaler/OptiScaler/wiki) and [Compatibility List](https://github.com/optiscaler/OptiScaler/wiki/Compatibility-List)?
 - [X] Yes
 - [ ] No

#### Please describe the issue and steps to reproduce it
I am using DLSS in game settings, and Optiscaler doesn't show FSR4 option. Optiscaler is in TRUE in OptiScaler.ini

#### I have attached
 - [X] OptiScaler.log _(set `LogLevel=0` and `LogToFile=true` in OptiScaler.ini, zip it if too big)_
 - [X] Screenshot of game folder _(where you placed Opti)_
 - [X] Screenshot of Opti overlay in-game _(opens with shortcut, default Insert)_

**Comment by thesnaglebeast** [comment]
I'm having the same issue with all my games using optiscaler. Optiscaler is functioning but I'm only able to select FSR 2 or FSR 3

Happened after installing the latest windows cumulative update and an AMD display update. Both updates were installed at the same time so I don't know which one is causing the issue but I suspect it's the AMD one.

**Comment by TheRazerMD** [comment]
It's the AMD Display Driver one. Windows Update just pushed a newer driver and for everyone who has driver updates turned on, it replaced the driver and changed the Windows folder of the FSR4 DLL (Opti relies on the registry telling it where to locate it). 
Nothing we can do on our side except tell people to either add the FSR4 DLL (amdxcffx64.dll) to the game folder where Optiscaler is located, or DDU and reinstall the proper driver. 

Edit: FSR4 DLL is linked on our [FSR4 Compatibility List](https://github.com/optiscaler/OptiScaler/wiki/FSR4-Compatibility-List).

**Comment by thesnaglebeast** [comment]
@TheRazerMD Can we edit / add an entry to the registry to point to the new Windows folder?

**Comment by TheRazerMD** [comment]
Not a permanent solution, nor would suggesting registry edits to randoms be any kind of a smart strategy.

Just supply the FSR4 DLL to Optiscaler until a new official AMD driver supercedes the WinUpdate one, and everything should be back in order.

**Comment by ebisettia** [comment]
> I'm having the same issue with all my games using optiscaler. Optiscaler is functioning but I'm only able to select FSR 2 or FSR 3
> 
> Happened after installing the latest windows cumulative update and an AMD display update. Both updates were installed at the same time so I don't know which one is causing the issue but I suspect it's the AMD one.

Yes, that is correct, because I remember it was working right, then today I realized that it wasn't.

**Comment by ebisettia** [comment]
> It's the AMD Display Driver one. Windows Update just pushed a newer driver and for everyone who has driver updates turned on, it replaced the driver and changed the Windows folder of the FSR4 DLL (Opti relies on the registry telling it where to locate it). Nothing we can do on our side except tell people to either add the FSR4 DLL (amdxcffx64.dll) to the game folder where Optiscaler is located, or DDU and reinstall the proper driver.
> 
> Edit: FSR4 DLL is linked on our [FSR4 Compatibility List](https://github.com/optiscaler/OptiScaler/wiki/FSR4-Compatibility-List).

So, to be 100% sure, if I DDU my rig and install the current AMD Drivers AKA Adrenaline, will everything be back to normal?

**Comment by TheRazerMD** [comment]
Yep, reinstalling e.g. 25.6.3 should fix the issue by either using DDU or Factory Reset in AMD installer. 
Only issue is Windows might replace the driver silently at some point again.

**Comment by gomicat** [comment]
I put the said DLL in my game/optiscale folder and it still doesn't show me any FSR options to select from. The game is Clair Obscur: Expedition 33. It seems to say FSR4 works on the compatibility list... does this make any sense? Do I need to add a line to the ini file under the input to add it to the menu?
